### ISSUE TITLE
Optimize Miner Fee Retrieval Without Using Private Key

### ISSUE THREAD

**Issue by kelefy** [james19870606/TronWeb#6]
```
tron.setup(privateKey: "privateKey") {_,_ in 
                    tron.estimateTRXTransferFee(toAddress: recipientAddress, amount: amount) { 
  }
}
```

hi, @james19870606 

Once the private key is input, it will work, but the private key is an encrypted field and cannot be accessed freely. Could you please optimize it to avoid using the private key to check the miner fee?

_Originally posted by @kelefy in https://github.com/james19870606/TronWeb/issues/5#issuecomment-2185489829_

**Comment by james19870606** [comment]
https://github.com/tronprotocol/tronweb/issues/401#issuecomment-1635232742

The bandwidth is calculated based on the transaction raw data length, you can get the length of transaction raw_data to get the estimated bandwidth.

A private key signature is required to obtain the transaction. Without the private key, there is no transaction, and thus the bandwidth consumption cannot be calculated. Alternatively, you can try providing any private key for the signature.
